<?php
$students = [
    'student1' => [
        'password' => 'piedad',
        'name' => 'Gerald F. Piedad',
        'age' => 20,
        'address' => 'Malolos, Bulacan',
        'student_no' => '202211093',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/gerald.jpeg'
    ],
    'student2' => [
        'password' => 'mendoza',
        'name' => 'Justin V. Mendoza',
        'age' => 20,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202212043',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/justin.jpeg'
    ],
    'student3' => [
        'password' => 'hernandez',
        'name' => 'Krisitan Lloyd DC. Hernandez',
        'age' => 20,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202211354',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/kristian.jpeg'
    ],
    'student4' => [
        'password' => 'baylon',
        'name' => 'John Philip Baylon',
        'age' => 20,
        'address' => 'Baliuag, Bulacan',
        'student_no' => '20210101',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/philip.jpeg'
    ],
    'student5' => [
        'password' => 'gutierrez',
        'name' => 'Daniel Gutierrez',
        'age' => 20,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202210328',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/daniel.jpeg'
    ],
    'student6' => [
        'password' => 'cruz',
        'name' => 'Jun Arvin Cruz',
        'age' => 20,
        'address' => 'Baliuag, Bulacan',
        'student_no' => '202210135',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/arvin.jpeg'
    ],
    'student7' => [
        'password' => 'coronel',
        'name' => 'Johanz Coronel',
        'age' => 20,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202210206',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/johanz.jpeg'
    ],
    'student8' => [
        'password' => 'caragos',
        'name' => 'John Kenneth Caragos',
        'age' => 25,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202210424',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/kenneth.jpeg'
    ],
    'student9' => [
        'password' => 'morana',
        'name' => 'Jonathan Nikolai Morana',
        'age' => 21,
        'address' => 'Pulilan, Bulacan',
        'student_no' => '202210227',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/jonathan.jpeg'
    ],
    '202210402' => [
        'password' => 'deguzman',
        'name' => 'Jayson Ynigo De Guzman',
        'age' => 21,
        'address' => 'Baliuag, Bulacan',
        'student_no' => '202210402',
        'course' => 'BSIT',
        'year' => 3,
        'section' => 'D',
        'institute' => 'IITI',
        'profile_pic' => 'assets/jayson.jpeg'
    ],
];
